import type { Metadata } from "next";
import "../style/globals.css";
import { Toaster } from "react-hot-toast";
import React from "react";
import { ThemeProvider } from "@/components/theme-provider";
import Sidebar from "@/components/sidebar";
import ModeToggle from "@/components/mode-toggle";
import { Inter as FontSans } from "next/font/google"
import {cn} from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// @ts-ignore
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
      )}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem={true}
          disableTransitionOnChange
        >
          <div className="flex flex-1">
            <Sidebar />
            <main className="w-full min-h-screen flex-col items-center justify-between p-6 lg:py-8">
              <Toaster />
              <ModeToggle/>
              {children}
            </main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
