"""Add AttendanceModel Fix Ok

Revision ID: 33e306f83347
Revises: 2046dc6f0dd1
Create Date: 2024-03-30 12:26:27.211095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33e306f83347'
down_revision: Union[str, None] = '2046dc6f0dd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
