"""Add AttendanceModel Fix Now

Revision ID: 538a391dc46d
Revises: e34265fa5b71
Create Date: 2024-03-30 12:19:55.819468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '538a391dc46d'
down_revision: Union[str, None] = 'e34265fa5b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
