"""Add AttendanceModel Fix

Revision ID: e34265fa5b71
Revises: 1d00d0a2b3f3
Create Date: 2024-03-30 12:15:56.204313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e34265fa5b71'
down_revision: Union[str, None] = '1d00d0a2b3f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
