"""fix optional forigenkey not null

Revision ID: 371e06f2b748
Revises: 17c73dc5da7f
Create Date: 2024-02-24 16:09:06.048487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '371e06f2b748'
down_revision: Union[str, None] = '17c73dc5da7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address', 'user_detail_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_detail', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_detail', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('address', 'user_detail_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
