"""Add AttendanceModel

Revision ID: 1d00d0a2b3f3
Revises: 062b05ca72a7
Create Date: 2024-03-30 11:52:15.089598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d00d0a2b3f3'
down_revision: Union[str, None] = '062b05ca72a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
