"""Add AttendanceModel Fix New

Revision ID: 2046dc6f0dd1
Revises: 538a391dc46d
Create Date: 2024-03-30 12:21:36.378437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2046dc6f0dd1'
down_revision: Union[str, None] = '538a391dc46d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
